### ISSUE TITLE
Add URL column to output

### ISSUE THREAD

**Issue by kennethjyang** [getgoji/goji-data-analysis#3]
So the extension can use the JSON file to dynamically check available websites

**Comment by jasmine-schoch** [comment]
the URLs added should be our own just in case the original spreadsheets get modified/taken down

**Comment by kennethjyang** [comment]
Oh I meant adding URLs to the brand websites. This is so we don't need to have that giant dictionary of website names to website URLs sitting in our javascript code. I'm trying to centralize any dynamic data like that into the data analysis step so in the event we have changes to the database we don't have to go looking in the extension code for things to also update. But yeah I will still probably add a step to cache the data for easier local edits.
